src/Uts/HotelBundle/Entity/SearchRequest.php
<?php

namespace Uts\HotelBundle\Entity;

use Doctrine\ORM\Mapping as ORM;
use Uts\HotelBundle\Validator\Constraints as UtsHotelAssert;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * Class SearchRequest
 * @package Uts\HotelBundle\Entity
 *
 * @ORM\Entity(repositoryClass="Uts\HotelBundle\Repository\SearchRequestRepository")
 * @ORM\Table(name="search_request")
 * @UtsHotelAssert\ValidSearchDates
 */
class SearchRequest
{
    const STATUS_NEW = 0;
    const STATUS_COMPLETE = 1;
    const STATUS_OLD = 2;
    const STATUS_ERROR = 3;

    /**
     * @ORM\Id
     * @ORM\Column(type="integer")
     * @ORM\GeneratedValue()
     * 
     * @var int
     */
    private $id;

    /**
     * @Assert\NotNull(message="Не указан город", groups={"search"})
     * @ORM\ManyToOne(targetEntity="City")
     * @var City
     */
    private $city;

    /**
     * @Assert\Date(message="Не указана дата заезда", groups={"search"})
     * @Assert\NotNull(message="Не указана дата заезда", groups={"search"})
     * @ORM\Column(type="date")
     * @var \DateTime
     */
    private $checkIn;

    /**
     * @Assert\Date(message="Не указана дата выезда", groups={"search"})
     * @Assert\NotNull(message="Не указана дата выезда", groups={"search"})
     * @ORM\Column(type="date")
     * @var \DateTime
     */
    private $checkOut;

    /**
     * @ORM\Column(type="integer")
     * @var int
     */
    private $adults = 1;

    /**
     * @ORM\Column(type="datetime")
     * @var \DateTime
     */
    private $createdAt;

    /**
     * @ORM\Column(type="integer")
     * @var int
     */
    private $status = self::STATUS_NEW;

    public function __construct()
    {
        $this->createdAt = new \DateTime();
    }

    /**
     * Get Id
     *
     * @return int
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Set checkIn
     *
     * @param \DateTime $checkIn
     * @return SearchRequest
     */
    public function setCheckIn($checkIn)
    {
        $this->checkIn = $checkIn;

        return $this;
    }

    /**
     * Get checkIn
     *
     * @return \DateTime 
     */
    public function getCheckIn()
    {
        return $this->checkIn;
    }

    /**
     * Set checkOut
     *
     * @param \DateTime $checkOut
     * @return SearchRequest
     */
    public function setCheckOut($checkOut)
    {
        $this->checkOut = $checkOut;

        return $this;
    }

    /**
     * Get checkOut
     *
     * @return \DateTime 
     */
    public function getCheckOut()
    {
        return $this->checkOut;
    }

    /**
     * Set adults
     *
     * @param integer $adults
     * @return SearchRequest
     */
    public function setAdults($adults)
    {
        $this->adults = $adults;

        return $this;
    }

    /**
     * Get adults
     *
     * @return integer 
     */
    public function getAdults()
    {
        return $this->adults;
    }

    /**
     * Get createdAt
     *
     * @return \DateTime 
     */
    public function getCreatedAt()
    {
        return $this->createdAt;
    }

    /**
     * Get status
     *
     * @return integer 
     */
    public function getStatus()
    {
        return $this->status;
    }

    /**
     * Set city
     *
     * @param \Uts\HotelBundle\Entity\City $city
     * @return SearchRequest
     */
    public function setCity(City $city = null)
    {
        $this->city = $city;

        return $this;
    }

    /**
     * Get city
     *
     * @return \Uts\HotelBundle\Entity\City 
     */
    public function getCity()
    {
        return $this->city;
    }

    public function markAsComplete()
    {
        $this->status = self::STATUS_COMPLETE;
    }

    public function markAsOld()
    {
        $this->status = self::STATUS_OLD;
    }

    public function markAsError()
    {
        $this->status = self::STATUS_ERROR;
    }

    public function isNew()
    {
        return $this->status == self::STATUS_NEW;
    }

    public function isComplete()
    {
        return $this->status == self::STATUS_COMPLETE;
    }

    public function isOld()
    {
        return $this->status == self::STATUS_OLD;
    }

    public function isError()
    {
        return $this->status == self::STATUS_ERROR;
    }

    /**
     * Set createdAt
     *
     * @param \DateTime $createdAt
     * @return SearchRequest
     */
    public function setCreatedAt($createdAt)
    {
        $this->createdAt = $createdAt;

        return $this;
    }

    /**
     * Set status
     *
     * @param integer $status
     * @return SearchRequest
     */
    public function setStatus($status)
    {
        $this->status = $status;

        return $this;
    }
}

src/Uts/HotelBundle/Entity/SearchResult.php
<?php

namespace Uts\HotelBundle\Entity;

use Doctrine\ORM\Mapping as ORM;
use Uts\HotelBundle\Entity\SpecialOffer;

/**
 * Результат поиска отелей
 *
 * @ORM\Entity(repositoryClass="Uts\HotelBundle\Repository\SearchResult")
 * @ORM\Table(name="search_result")
 */
class SearchResult
{
    /**
     * @ORM\Id
     * @ORM\Column(type="integer")
     * @ORM\GeneratedValue()
     *
     * @var int
     */
    private $id;

    /**
     * @ORM\ManyToOne(targetEntity="SearchRequest")
     * @var
     */
    private $request;

    /**
     * @ORM\ManyToOne(targetEntity="Hotel", inversedBy="searchResults")
     * @var Hotel
     */
    private $hotel;

    /**
     * @ORM\ManyToOne(targetEntity="SpecialOffer")
     * @var SpecialOffer
     */
    private $specialOffer;

    /**
     * @ORM\ManyToOne(targetEntity="Meal")
     * @var Meal
     */
    private $meal;

    /**
     * @ORM\Column(type="decimal",scale=2,precision=10)
     * @var string
     */
    private $price;

    /**
     * @ORM\Column(type="decimal",scale=2,precision=10, nullable=true)
     * @var string
     */
    private $discount;

    /**
     * @ORM\Column(length=3)
     * @var string
     */
    private $currency;

    /**
     * @ORM\Column(length=255)
     * @var string
     */
    private $roomName;


    /**
     * Get id
     *
     * @return integer 
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Set price
     *
     * @param string $price
     * @return SearchResult
     */
    public function setPrice($price)
    {
        $this->price = $price;

        return $this;
    }

    /**
     * Get price
     *
     * @return string 
     */
    public function getPrice()
    {
        return $this->price;
    }

    /**
     * Set currency
     *
     * @param string $currency
     * @return SearchResult
     */
    public function setCurrency($currency)
    {
        $this->currency = $currency;

        return $this;
    }

    /**
     * Get currency
     *
     * @return string 
     */
    public function getCurrency()
    {
        return $this->currency;
    }

    /**
     * Set roomName
     *
     * @param string $roomName
     * @return SearchResult
     */
    public function setRoomName($roomName)
    {
        $this->roomName = $roomName;

        return $this;
    }

    /**
     * Get roomName
     *
     * @return string 
     */
    public function getRoomName()
    {
        return $this->roomName;
    }

    /**
     * Set request
     *
     * @param \Uts\HotelBundle\Entity\SearchRequest $request
     * @return SearchResult
     */
    public function setRequest(SearchRequest $request = null)
    {
        $this->request = $request;

        return $this;
    }

    /**
     * Get request
     *
     * @return \Uts\HotelBundle\Entity\SearchRequest 
     */
    public function getRequest()
    {
        return $this->request;
    }

    /**
     * Set hotel
     *
     * @param \Uts\HotelBundle\Entity\Hotel $hotel
     * @return SearchResult
     */
    public function setHotel(Hotel $hotel = null)
    {
        $this->hotel = $hotel;

        return $this;
    }

    /**
     * Get hotel
     *
     * @return \Uts\HotelBundle\Entity\Hotel 
     */
    public function getHotel()
    {
        return $this->hotel;
    }

    /**
     * Set meal
     *
     * @param \Uts\HotelBundle\Entity\Meal $meal
     * @return SearchResult
     */
    public function setMeal(Meal $meal = null)
    {
        $this->meal = $meal;

        return $this;
    }

    /**
     * Get meal
     *
     * @return \Uts\HotelBundle\Entity\Meal
     */
    public function getMeal()
    {
        return $this->meal;
    }

    public function getMealName()
    {
        return $this->meal &&
            !in_array($this->meal->getId(), array(Meal::MEAL_UNKNOWN, Meal::MEAL_WITHOUT)) ?
            $this->meal->getName() : '';
    }

    /**
     * Set specialOffer
     *
     * @param SpecialOffer $specialOffer
     * @return SearchResult
     */
    public function setSpecialOffer(SpecialOffer $specialOffer = null)
    {
        $this->specialOffer = $specialOffer;

        return $this;
    }

    /**
     * Get specialOffer
     *
     * @return SpecialOffer
     */
    public function getSpecialOffer()
    {
        return $this->specialOffer;
    }

    /**
     * @return string
     */
    public function getDiscount()
    {
        return $this->discount;
    }

    /**
     * @param string $discount
     * @return $this
     */
    public function setDiscount($discount)
    {
        $this->discount = $discount;

        return $this;
    }
}

src/Uts/HotelBundle/Controller/DefaultController.php
<?php

namespace Uts\HotelBundle\Controller;

use Doctrine\ORM\EntityManager;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Symfony\Component\HttpFoundation\RedirectResponse;
use Symfony\Component\HttpFoundation\Response;
use Uts\HotelBundle\Entity\SearchRequest;
use Symfony\Component\HttpFoundation\Request;

class DefaultController extends Controller
{
    public function indexAction(Request $request)
    {
        $objSearchForm = $this->createForm('uts_hotel_search_request', new SearchRequest());
        $objSearchForm->handleRequest($request);
        return $this->render('UtsHotelBundle:Default:index.html.twig', array('searchForm' => $objSearchForm->createView()));
    }

    public function processAction(Request $request)
    {
        $objSearchForm = $this->createForm('uts_hotel_search_request', new SearchRequest());
        $objSearchForm->submit($request->query->get($objSearchForm->getName()), false);
        if ($objSearchForm->isValid()) {
            $objSearchRequest = $objSearchForm->getData();

            /* @var $objSearchRequest SearchRequest */
            $em = $this->getDoctrine()->getManagerForClass('UtsHotelBundle:SearchRequest');

            $sameSearchRequest = $em->getRepository('UtsHotelBundle:SearchRequest')->findSameSearchRequest($objSearchRequest);

            if($sameSearchRequest === null) {
                $em->persist($objSearchRequest);
                $em->flush();

                try {
                    $objSearcher = $this->get('uts_hotel.searcher');
                    $results = $objSearcher->search($objSearchRequest);
                    foreach ($results as $objResult) {
                        $em->persist($objResult);
                    }
                    $objSearchRequest->markAsComplete();
                    $em->flush();
                } catch (\Exception $err) {
                    $objSearchRequest->markAsError();
                    $em->flush();
                    throw $err;
                }
            } else {
                $objSearchRequest = $sameSearchRequest;
            }

            return new RedirectResponse(
                $this->get('router')
                    ->generate('uts_hotel_search_results', array('searchId' => $objSearchRequest->getId()))
            );
        } else {
            return $this->render('UtsHotelBundle:Default:index.html.twig', array('searchForm' => $objSearchForm->createView()));
        }
    }

    public function resultsAction($searchId, $page)
    {
        /** @var EntityManager $em */
        $em = $this->getDoctrine()->getManager();
        $objSearchRequest = $em->find('UtsHotelBundle:SearchRequest', $searchId);
        if (!$objSearchRequest) {
            $this->createNotFoundException();
        }

        $objSearchForm = $this->createForm('uts_hotel_search_request', $objSearchRequest);
        $templateVars = array(
            'searchForm' => $objSearchForm->createView(),
            'request' => $objSearchRequest
        );
        if ($objSearchRequest->isComplete() || $objSearchRequest->isOld()) {
            $hotelRepository = $em->getRepository('UtsHotelBundle:Hotel');

            $query = $hotelRepository->getHotelListQueryBuilderByRequestId($searchId);

            $paginator = $this->get('knp_paginator');
            $pagination = $paginator->paginate($query, $page, 50);
            $templateVars['pagination'] = $pagination;
        }
        return $this->render('UtsHotelBundle:Default:results.html.twig', $templateVars);
    }
}

src/Uts/HotelBundle/Resources/views/Default/index.html.twig
{% extends 'base.html.twig' %}

{% block test_active %}class="active"{% endblock %}

{% form_theme searchForm 'UtsHotelBundle:Form:search.html.twig' %}

{% block body %}
    <div class="jumbotron">
        <h1>Поиск отелей</h1>
        {{ form(searchForm) }}
    </div>
{% endblock %}

src/Uts/HotelBundle/Resources/views/Default/results.html.twig
{% extends 'UtsHotelBundle:Default:index.html.twig' %}

{% block body %}
    <div class="jumbotron">
        <h1>Поиск отелей</h1>
        {{ form(searchForm) }}
    </div>
    <div class="row">
        <div class="col-lg-12"><h1>{{ request.city.name }} {{ request.checkIn|date('d.m.Y') }} - {{ request.checkOut|date('d.m.Y') }}</h1></div>
    </div>
    {% if request.error %}
        <div class="row">
            <div class="col-lg-12 alert alert-danger">
                Поиск завершился ошибкой, попробуйте повторить или изменить параметры
            </div>
        </div>
    {% elseif request.new %}
        <div class="row">
            <div class="col-lg-12 alert alert-warning">
                Поиск ещё не был завершен. Повторите попытку позже.
            </div>
        </div>
    {% else %}
        {# total items count #}
        <div class="row">
            <div class="col-lg-12 text-muted">
                Найдено отелей: {{ pagination.getTotalItemCount }}
            </div>
        </div>
        <div class="center-block">
            {{ knp_pagination_render(pagination) }}
        </div>
        {# table body #}
        {% for hotel in pagination.items %}
            <div class="row bg-info">
                <div class="col-lg-1">{{ loop.index }}</div>
                <div class="col-lg-6">
                    <span class="text-capitalize">{{ hotel.name }}</span>
                </div>
                <div class="col-lg-2">от {{ hotel.searchResults.first.price }} {{ hotel.searchResults.first.currency }}</div>
            </div>

            {% for item in hotel.searchResults %}

                <div class="row">
                    <div class="col-lg-1">&nbsp;</div>
                    <div class="col-lg-6">
                        <span class="text-primary">{{ item.roomName }}</span>
                        {% if(item.mealName) %}
                        <span class="text-muted">({{ item.mealName }})</span>
                        {% endif %}
                    </div>
                    <div class="col-lg-2">
                        {% if item.specialOffer %}
                            <span style="text-decoration: line-through; color: red">{{ item.price }}</span>
                            {{ item.price - item.discount }}
                        {% else %}
                            {{ item.price }}
                        {% endif %}

                        {{ item.currency }}

                    </div>
                        <div class="col-lg-3">

                        {% if item.specialOffer %}
                            "{{ item.specialOffer.name }}"<br>
                            скидка: <strong>{{ item.discount }} {{ item.currency }}
                            {% if item.specialOffer.discountType == 'm' %}
                                ( {{ item.specialOffer.discountValue }} % )
                            {% endif %}
                                </strong>
                        {% endif %}

                        </div>
                </div>

            {% endfor %}
        {% endfor %}
        {# display navigation #}
        <div class="center-block">
            {{ knp_pagination_render(pagination) }}
        </div>
    {% endif %}
{% endblock %}